name: "CI"
on:
  push

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  # More info: https://stackoverflow.com/a/68422069/253468:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@943fa2f540b5a8cc631ac443c265a3aa59ebcb7c # v3
    permissions:
      contents: read
      security-events: write
      actions: read


  verify:
    name: "🛠 Build & Verify"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project."
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          check
          lint
          lintVerifyCount

      - name: "Upload 'Lint Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Lint Results'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/build/reports/lint-results*.*


  build-quick:
    name: "🧪 Quick Lint"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project."
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          -Plints.check.only.specific=true
          lint
          lintVerifyCount

      - name: "Upload 'Lint Results (Quick)' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Lint Results (Quick)'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/build/reports/lint-results*.*


  build-all:
    name: "🔨 Build All modules"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} ref in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project."
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          -Plints.use.all.versions=true
          assemble
